### ISSUE TITLE
after running docker-compose up

### ISSUE THREAD

**Issue by scharph** [arno01/taiga#5]
taiga_1     |   Applying webhooks.0002_webhook_name... OK
taiga_1     |   Applying webhooks.0003_auto_20150122_1021... OK
taiga_1     |   Applying webhooks.0004_auto_20150202_0834... OK
taiga_1     |   Applying webhooks.0005_auto_20150505_1639... OK
taiga_1     |   Applying wiki.0004_auto_20160928_0540...Trying import local.py settings...
taiga_1     |  OK
taiga_1     | Trying import local.py settings...
taiga_1     | Trying import local.py settings...
taiga_1     | Installed 1 object(s) from 1 fixture(s)
taiga_1     | Trying import local.py settings...
taiga_1     | Installed 2 object(s) from 1 fixture(s)
taiga_1     | Trying import local.py settings...
taiga_1     | First run: A new user admin with password 123123 has been created. Please change the password once you login.
taiga_1     | Trying import local.py settings...
taiga_1     | processing file django.po in /opt/taiga/taiga-back/taiga/locale/nb/LC_MESSAGES
taiga_1     | processing file django.po in /opt/taiga/taiga-back/taiga/locale/nl/LC_MESSAGES
taiga_1     | processing file django.po in /opt/taiga/taiga-back/taiga/locale/fi/LC_MESSAGES
taiga_1     | processing file django.po in /opt/taiga/taiga-back/taiga/locale/zh-Hant/LC_MESSAGES
taiga_1     | processing file django.po in /opt/taiga/taiga-back/taiga/locale/ru/LC_MESSAGES
taiga_1     | processing file django.po in /opt/taiga/taiga-back/taiga/locale/de/LC_MESSAGES
taiga_1     | processing file django.po in /opt/taiga/taiga-back/taiga/locale/it/LC_MESSAGES
taiga_1     | processing file django.po in /opt/taiga/taiga-back/taiga/locale/pl/LC_MESSAGES
taiga_1     | processing file django.po in /opt/taiga/taiga-back/taiga/locale/es/LC_MESSAGES
taiga_1     | processing file django.po in /opt/taiga/taiga-back/taiga/locale/tr/LC_MESSAGES
taiga_1     | processing file django.po in /opt/taiga/taiga-back/taiga/locale/en/LC_MESSAGES
taiga_1     | processing file django.po in /opt/taiga/taiga-back/taiga/locale/pt_BR/LC_MESSAGES
taiga_1     | processing file django.po in /opt/taiga/taiga-back/taiga/locale/sv/LC_MESSAGES
taiga_1     | processing file django.po in /opt/taiga/taiga-back/taiga/locale/ca/LC_MESSAGES
taiga_1     | processing file django.po in /opt/taiga/taiga-back/taiga/locale/fr/LC_MESSAGES
taiga_1     | Trying import local.py settings...
taiga_1     | Raven is not configured (logging is disabled). Please see the documentation for more information.
taiga_1     | Copying '/opt/taiga/venvtaiga/lib/python3.4/site-packages/django/contrib/admin/static/admin/fonts/LICENSE.txt'
taiga_1     | Traceback (most recent call last):
taiga_1     |   File "manage.py", line 29, in <module>
taiga_1     |     execute_from_command_line(sys.argv)
taiga_1     |   File "/opt/taiga/venvtaiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
taiga_1     |     utility.execute()
taiga_1     |   File "/opt/taiga/venvtaiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 345, in execute
taiga_1     |     self.fetch_command(subcommand).run_from_argv(self.argv)
taiga_1     |   File "/opt/taiga/venvtaiga/lib/python3.4/site-packages/django/core/management/base.py", line 348, in run_from_argv
taiga_1     |     self.execute(*args, **cmd_options)
taiga_1     |   File "/opt/taiga/venvtaiga/lib/python3.4/site-packages/raven/contrib/django/management/__init__.py", line 41, in new_execute
taiga_1     |     return original_func(self, *args, **kwargs)
taiga_1     |   File "/opt/taiga/venvtaiga/lib/python3.4/site-packages/django/core/management/base.py", line 399, in execute
taiga_1     |     output = self.handle(*args, **options)
taiga_1     |   File "/opt/taiga/venvtaiga/lib/python3.4/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 176, in handle
taiga_1     |     collected = self.collect()
taiga_1     |   File "/opt/taiga/venvtaiga/lib/python3.4/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 107, in collect
taiga_1     |     handler(path, prefixed_path, storage)
taiga_1     |   File "/opt/taiga/venvtaiga/lib/python3.4/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 331, in copy_file
taiga_1     |     self.storage.save(prefixed_path, source_file)
taiga_1     |   File "/opt/taiga/venvtaiga/lib/python3.4/site-packages/django/core/files/storage.py", line 63, in save
taiga_1     |     name = self._save(name, content)
taiga_1     |   File "/opt/taiga/venvtaiga/lib/python3.4/site-packages/django/core/files/storage.py", line 222, in _save
taiga_1     |     os.makedirs(directory)
taiga_1     |   File "/opt/taiga/venvtaiga/lib/python3.4/os.py", line 227, in makedirs
taiga_1     |     makedirs(head, mode, exist_ok)
taiga_1     |   File "/opt/taiga/venvtaiga/lib/python3.4/os.py", line 237, in makedirs
taiga_1     |     mkdir(name, mode)
taiga_1     | PermissionError: [Errno 13] Permission denied: '/opt/taiga/static/admin'
taiga_1     | 2017-05-01 22:59:10 circus[122] [INFO] Starting master on pid 122
taiga_1     | 2017-05-01 22:59:10 circus[122] [INFO] Arbiter now waiting for commands
taiga_1     | 2017-05-01 22:59:10 circus[122] [INFO] taiga started
taiga_1     | 2017-05-01 22:59:10 circus[122] [INFO] circusd-stats started
taiga_1     | 2017-05-01 22:59:11 circus[127] [INFO] Starting the stats streamer

can someone help me?

**Comment by arno01** [comment]
@scharph I have pushed fixes in https://github.com/arno01/taiga/commit/590e22b609b2349aad1fa0feb61cd906de0e9f82

The automated build is in progress now https://hub.docker.com/r/andrey01/taiga/builds/bqw6zpob475kxj4dpkbcrva/

Once it is done, please try to re-run:
```
docker-compose pull
docker-compose up
```

Please re-open this issue in case of problems.

Thx.
