### ISSUE TITLE
BUG: current version has an issue with the epics view

### ISSUE THREAD

**Issue by sopitz** [arno01/taiga#8]
I just reported an issue with Taiga [here](https://github.com/taigaio/taiga-front/issues/1357).

Could you update the images to make sure everyone can get the fix please?! Thanks!

**Comment by arno01** [comment]
@sopitz thanks for reporting!

I have just triggered the rebuild https://hub.docker.com/r/andrey01/taiga/builds/bdtxjsn7trgynwjzbntsz3f/

Though, did they push the fix to the upstream?

**Comment by sopitz** [comment]
It's just a git pull on the taiga-front-dist that fixes the problem. So your build should work as far as I could see.

**Comment by arno01** [comment]
@sopitz build finished 2h ago, could you please confirm the issue has gone?
Thanks.

**Comment by sopitz** [comment]
@arno01 yup. It works now. Thanks for the quick fix!
